### ISSUE TITLE
[Feature request] Adaptive strictness

### ISSUE THREAD

**Issue by van-de-bugger** [plicease/Dist-Zilla-Plugin-Test-Version#5]
I would like to use `Test::Version` with `is_strict = 1`. However, it effectively prohibits any trial versions, because any trial version (which contains an underscore) does not pass the test. I have few options to make a trial release:
1. Drop `is_strict` completely — but I want it for non-trial releases.
2. Modify the parameter each before and after each trial release — works but inconvenient.

I would be nice if `Test::Version` is able to use "adaptive strictness":  i. e. perform strict check for non-trial release and perform lax check for trial release.

**Comment by plicease** [comment]
This is a good idea!  I'll see if I can implement it.

**Comment by van-de-bugger** [comment]
Implementation seems trivial. The only problem is interface design.

For example, `is_strict` could be extended to accept either `0`, `1`, or `adaptive`:

```
use Moose::Util::TypeConstraints qw{ enum };

...

has is_strict => (
  is => 'bare',
  isa => enum( [ qw{ 0 adaptive 1 } ] ),
  default => sub { '0' },
);

sub is_strict {
    my ( $self ) = @_;
    if ( $self->{ is_strict } eq 'adaptive' ) {
        return $self->zilla->is_trial ? '0' : '1';
    } else {
        return $self->{ is_strict };
    };
}
```
